### ISSUE TITLE
Crash in non-English Windows

### ISSUE THREAD

**Issue by tskarman** [cbaxter/Harvester#23]
Harvester per default crashes in a German Windows.

I usually fix it by replacing `Everyone` with `Jeder` in the `*.config`.

So

`<listener binding="\\.\pipe\Harvester" mutex="HarvesterMutex" identity="Everybody" type="Harvester.Core.Messaging.Sources.NamedPipe.PipeMessageListener, Harvester.Core"/>`

becomes

`<listener binding="\\.\pipe\Harvester" mutex="HarvesterMutex" identity="Jeder" type="Harvester.Core.Messaging.Sources.NamedPipe.PipeMessageListener, Harvester.Core"/>`

I have no real suggestion on how to fix this. [`WellKnownSidType`](http://msdn.microsoft.com/en-us/library/system.security.principal.wellknownsidtype(v=vs.110).aspx) looks like a place to start. 

Some other results:
* http://stackoverflow.com/questions/4614697/how-to-get-the-identityreference-for-everyone-to-create-mutexaccessrule-on-loc
* http://stackoverflow.com/questions/663332/localized-group-name

A quick GitHub search over the repo revealed that it might not be limited to the config files as the string is used in some source files.

By the way - thank you for this project.

**Comment by cbaxter** [comment]
@tskarman I missed this issue being logged; I will investigate the suggested solution.
